version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    container_name: backend
    ports:
      - "22:22"
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
      - ./docker/backend/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db

  # frontend:
    # build:
      # context: .
      # dockerfile: ./docker/frontend/Dockerfile
    # container_name: frontend
    # restart: unless-stopped
    # tty: true
   #  working_dir: /var/www
    # ports:
    #   - "8080:8080"
   #  volumes:
     #  - ./frontend:/var/www

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - backend

  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
    driver: local
